// Include internal libraries...
#include "openWeatherLibrary/openWeatherLibrary.h"

// Definition of the main function...
int main() {

	// Call the 'getWeather' function defined in the 'openWeatherLibrary' internal library...
	getWeather();

	// Return 0 (execution without error)...
	return 0;
}
