// Include internal libraries...
#include "openWeatherLibrary/openWeatherLibrary.h"

// Definition of the main function...
int main() {

	// Call the first 'getWeather' function...
	getWeather("", "");

	// Return 0 (execution without error)...
	return 0;
}
